apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-1-dev-vault-sync
  namespace: app-1-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-vault
  target:
    name: app-1-dev-secrets
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: secret/data/apps/dev/app-1