apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-1-prod-vault-sync
  namespace: app-1-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-vault
  target:
    name: app-1-prod-secrets
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: secret/data/apps/prod/app-1