# name: Deploy to EKS
# on:
#   push:
#     branches: [ main, dev ]
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     permissions:
#       id-token: write
#       contents: write
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3
#       - name: Configure AWS Credentials (OIDC)
#         uses: aws-actions/configure-aws-credentials@v2
#         with:
#           role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
#           aws-region: us-east-1
#       - name: Login to ECR
#         uses: aws-actions/amazon-ecr-login@v1
#       - name: Build and Push
#         run: |
#           IMAGE_TAG="v1.${{ github.run_number }}"
#           docker build -t ${{ secrets.ECR_REPO_URL }}:$IMAGE_TAG .
#           docker push ${{ secrets.ECR_REPO_URL }}:$IMAGE_TAG
#           echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
#       - name: Update Kubernetes Manifest
#         run: |
#           sed -i "s|image:.*|image: ${{ secrets.ECR_REPO_URL }}:${{ env.IMAGE_TAG }}|g" k8s/dev/deployment.yaml
#           git config user.name "github-actions"
#           git config user.email "actions@github.com"
#           git add .
#           git commit -m "Update image to ${{ env.IMAGE_TAG }} [skip ci]"
#           git push