name: Test Docker Hub Build and Push

on:
  push:
    branches: [ main, dev ]

jobs:
  semgrep:
    name: Security Scan
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@v3
      - name: Run Semgrep
        run: semgrep scan --config auto --error

  docker:
    name: Build and Push
    runs-on: ubuntu-latest
    needs: semgrep  # This ensures the scan passes before building the image
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ahmedmosaad594/ahmed-mosaad-resume:latest
            ahmedmosaad594/ahmed-mosaad-resume:v1.${{ github.run_number }}